#services:
#  mariadb:
#    image: mariadb:latest
#    env_file:
#      - docker.env
#    environment:
#      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
#      MARIADB_DATABASE: ${MARIADB_NAME}
#      MARIADB_USER: ${MARIADB_USER}
#      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#      - ./database/db_data:/var/lib/mysql
#    restart: always
#
#  client-api:
#    image: client-api
#    build:
#      context: ./back/client
#      dockerfile: Dockerfile
#      target: prod
#    volumes:
#      - .:/app/client-api
#      - /app/node_modules
#    ports:
#      - 3333:3000
#    env_file:
#      - docker.env
#    depends_on:
#      - mariadb
#    command: pnpm start:dev
#
#volumes:
#  db_data:
#networks:
#  app-network:
#    driver: bridge
#
###  api:
###    container_name: nestjs
###    image: nestjs-dev
###    restart: unless-stopped
###    build:
###      context: ./backend
###      dockerfile: Dockerfile
###      # ✨ Target the dev stage
###      target: dev
###    # Mount host directory to docker container to support watch mode
###    volumes:
###      - .:/app/backend
###      # This ensures that the NestJS container manages the node_modules folder
###      # rather than synchronizes it with the host machine
###      - /app/node_modules
###    env_file:
###      - docker.env
###    ports:
###      - 3333:3000
###    #    networks:
###    #      - nest
###    #    depends_on:
###    #      - postgres
###    command: pnpm start:dev
##  frontend:
##    container_name: vuejs-dev
##    build:
##      context: ./frontend
##      dockerfile: Dockerfile
##      target: dev
##    depends_on:
##      - api
##    volumes:
##      - .:/app/frontend
##      - /app/node_modules
##    ports:
##      - 5173:5173
##  # ...other services
#
#
services:
  db:
    container_name: mariadb
    restart: always
#    image: mariadb:latest
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/mariadb-data:/var/lib/mysql
      - ./database/dump.sql:/dump.sql
    ports:
      - ${MYSQL_PORT}:3306
    command:




