services:
  front:
    container_name: front
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - back-client
      - back-events
  back-client:
    container_name: back-client
    restart: always
    build:
      context: ./back/client
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./docker/client-service/.env
    ports:
      - 3000:3000
    depends_on:
      - mariadb
    networks:
      - app-network

  back-events:
    container_name: back-events
    restart: always
    build:
      context: ./back/eventservice
      dockerfile: Dockerfile
      target: prod
    env_file:
      - ./docker/events-service/.env
    networks:
      - app-network

    # TODO - remove this line
    ports:
      - 3001:3001
    depends_on:
      - mariadb
  mariadb:
    container_name: mariadb
    restart: always
#    image: mariadb:latest
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./database/mariadb-data:/var/lib/mysql
      - ./database/dump.sql:/dump.sql
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
