#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
#npx lint-staged

# Client side
echo "Running lint-staged for frontend"
cd frontend && npm run lint && npm run format && npm run build
#tsc --noEmit

# Server side
#cd ../backend && npm run lint && npm run format
#tsc --noEmit
#
