#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
#npx lint-staged

# Client side
cd client && npm run lint && npm run format
tsc --noEmit

# Server side
cd ../epicroad-api && npm run lint && npm run format
tsc --noEmit

