name: CI Workflow

on:
  push:
    branches: [setup/cicd]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-keys.outputs.backend }}-${{ steps.cache-keys.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - id: cache-keys
        run: |
          echo "::set-output name=backend::$(find backend -type f -exec md5sum {} + | sort -k 2 | md5sum | awk '{print $1}')"
          echo "::set-output name=frontend::$(find frontend -type f -exec md5sum {} + | sort -k 2 | md5sum | awk '{print $1}')"
  build-and-test:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.X, 21.X]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
                - name: Run startdocker.sh
